In [81]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [82]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [83]:
# Coordenadas P_1
p1n = 2_457.897
p1e =   893.987
pi1 = np.array((p1e, p1n), dtype=np.float_)
pi1

array([ 893.987, 2457.897])

In [84]:
# Coordenadas P_2
p2n = 2_798.806
p2e = 1_000.086
pi2 = np.array((p2e, p2n), dtype=np.float_)
pi2

array([1000.086, 2798.806])

In [85]:
pi_2 = np.pi / 2
def pendiente(initial_point, final_point):
    return np.diff(np.stack((initial_point, final_point), axis=1), axis=1)
def angle(initial_point, final_point):
    pendiente_ = pendiente(initial_point, final_point)
    return np.arctan(pendiente_[1] / pendiente_[0])
def azimut_between_2_points(initial_point, final_point):
    return pi_2 - angle(initial_point, final_point)
def diferencia_pitagorica(initial_point, final_point):
    array = pendiente(initial_point, final_point)
    return np.sqrt(np.sum(array**2))

In [86]:
angle_1 = angle(pi1, pi2)
np.rad2deg(angle_1)

array([72.71261415])

In [87]:
az_rect = azimut_between_2_points(pi1, pi2)
np.rad2deg(az_rect)

array([17.28738585])

In [88]:
fig, ax = plt.subplots(figsize=(8,8))
coordinates = np.stack((pi1, pi2), axis=1)
ax.set_aspect(1)
ax.scatter(*coordinates, c="blue")
ax.annotate('$P_i 1$', xy=pi1, xytext=pi1+20000,
            arrowprops=dict(facecolor='black', shrink=0.05))
ax.annotate('$P_i 2$', xy=pi2, xytext=pi2+20000,
            arrowprops=dict(facecolor='black', shrink=0.05))
plt.show()

In [ ]:
# from geometry.module import *
from geometry.st import *
from geometry.diag import *
from geometry.pc import *

In [ ]:
Az_init = np.deg2rad(114.80789)
angle_temp1 = Az_init - pi_2 + angle_1
# print(np.rad2deg(angle_temp1))
Az_2 = azimut_between_2_points(pi1, pi2)
print(np.rad2deg(Az_2))

[17.28738585]


In [ ]:
np.rad2deg(Az_init)

114.80789000000001

In [ ]:
# Datos curva 1
radios_angulos_1 = np.array(
    [
        (267.880, float(angle_temp1)),
    ]
)
radios_angulos_1

array([[267.88      ,   1.70205389]])

In [ ]:
print(np.rad2deg(radios_angulos_1[0,1]))

97.52050415111374


In [ ]:
np.rad2deg(angle_1)

array([72.71261415])

In [ ]:
# calculo subtangentes
subtangentes = st_vec(radios_angulos_1)
subtangentes

array([305.5688757])

In [ ]:
diag_vec(radios_angulos_1)

array([[305.5688757 ,   1.70205389]])

In [ ]:
pc1 = 18_980.681
cotas_1 = p_total(radios_angulos_1, ci=pc1)
cotas_1

array([18980.681     , 19436.62719489])

In [ ]:
print(np.rad2deg(angle_1))

[72.71261415]


In [ ]:
# Datos curva 2
rumbo = np.deg2rad(76.80976)
angle_temp2 = angle_1 + pi_2 - rumbo
radios_angulos_2 = np.array(
    [
        ( 98.979, float(angle_temp2))
    ]
)
radios_angulos_2

array([[98.979     ,  1.49928764]])

In [ ]:
print(np.rad2deg(radios_angulos_2[0,1]))

85.90285415111371


In [ ]:
cotas_2 = p_total(radios_angulos_2, ci=0)
cotas_2

array([  0.       , 148.3979915])

In [ ]:
cota_conexion = cotas_1[-1] + 560# diferencia_pitagorica(p1)
cotas_2 = p_total(radios_angulos_2, ci=cota_conexion)
cotas_2

array([19996.62719489, 20145.02518638])

In [ ]:
def coor(p_init, length, azimut):
    return p_init + length*np.array([np.sin(azimut), np.cos(azimut)])

In [ ]:
Az_left = np.pi + Az_init
len_left = float(st_vec(radios_angulos_1))
pc1_coor = coor(pi1, len_left, Az_left)
pc1_coor

array([ 893709.62910918, 2458025.20969823])

In [ ]:
cotas = np.stack((cotas_1, cotas_2), axis=0).ravel()
cotas

array([18980.681     , 19436.62719489, 19996.62719489, 20145.02518638])

In [ ]:
diferencia_pitagorica(pi1, pi2)

357037.7348152433

In [ ]:
pt1_coor = pc1_coor(pc1_coor, , Az_init - radios_angulos_1[0,1] / 2 )

In [ ]:
len_right = float(st_vec(radios_angulos_2))
pc2_coor = coor(pt1_coor, diferencia_pitagorica(pi1, pi2) - len_left - len_right, az_rect)
pc2_coor

array([[ 999967.81418422, 2563877.81418422],
       [1234516.25458986, 2798426.25458986]])